# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dac817d5968d0fface0a0ff03cfdfdf6d6bc5126c9e18916fcbe28232be7c4d8e22a27c795e670ae2c2233f3ef2fde4f6e6281f108e406b7995f975c7c154ccc

test:
  secret_key_base: d3c0ea2cfd9f797a6a55107de892a79bf2c6dee083a7be5d085408c811bb9f19b991bb06426bbb26c50ad3031ddc941df7722ffffe3b3badefbfcf3323ff2f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
